### ISSUE TITLE
Use admin account as payer on all outgoing transactions

### ISSUE THREAD

**Issue by psiemens** [flow-hydraulics/flow-wallet-api#152] opened 2021-08-25 05:58 UTC
This issue was originally opened here by @tehranifar on July 28, 2021: https://github.com/onflow/wallet-api/issues/12

> We expect the admin account to contain enough FLOW to compensate for all custodial accounts' transactions.
>
> Some endpoints (like FT withdrawal) use the user account as the payer, thus running into problems when transactions fail and the storage falls below the minimum.
>
> All outgoing transactions from wallet-api should use the admin account as payer.

From @uhbif19:
> @tehranifar
> 
> It looks to me that all transactions send by hand are paid by user. Flow are taken from account after each transaction. Am I correct?

From @tehranifar:
> Yes, designating the admin account as payer will automatically make it pay for user transactions.

From @uhbif19:
> I am not sure what you mean. 'designating the admin account as payer' - is that something possible in Wallet API? Or your answer is about situation when working with a regular Flow client libruary?

**Comment by latenssi** [comment] 2021-08-25 06:19
Closing as duplicate of #139

**Closed by latenssi** 2021-08-25 06:19 UTC
Labels: duplicate
